### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by datakurre** [datakurre/collective.recipe.nix#1]
A quick issue for me for ideas and fixes:
- [ ] write about differences from pypi2nix and friends (In short, I want to be able to produce OOTB usable Nix expressions which can easily be updated. Sometime this requires configuration and CFG is easy for that.)
- [ ] cleanup resulting expression from empty buildInputs and propagatedBuildInputs
- [ ] add option for python version (e.g. python35 requires `with python35Packages;` before buildPythonPackage
- [ ] add option for shellHook code
- [ ] add shellHook with PYTHONPATH to developed packages 
- [ ] add standalone shellscript for using the recipe directly, e.g. against requirements.txt (while using buildout in the background in a tmp directory)

**Comment by datakurre** [comment]
@cillianderoiste RFC on how c.recipe.nix could be made better.
